"""`rite.py migrate` — adopt a legacy backlog in place.

`--from frontmatter`: cycles from before the JSON state (Rite up to 0.13) keep their state in the
frontmatter of each item and of the progress file. The migration moves it to `progress.json` and
`fixes.json`, leaves each item file with its `id` only, and changes nothing else in any file. It
checks its own work before writing a byte: the cycles read back from the JSON must equal the cycles
read from the frontmatter, item by item and field by field.

`--from graph`: progress files written before the dependency graph became a generated view keep a
hand-drawn mermaid block. The migration swaps that block for the generated region (rendered from each
task's `depends_on`) and keeps every other line. An edge the hand-drawn graph has and `depends_on`
lacks is reported, never added: the JSON is the source, and the operator decides.

`--from we2002`:

The legacy system kept state in three places (frontmatter, progress tables with emoji, dates in table
columns). Migration makes frontmatter the single source: it reads the tables, writes the state into
each item's frontmatter, replaces the tables with generated regions, and maps Portuguese vocabulary
to Rite's closed vocabulary. No file is renamed or moved; run it on a branch and review the diff.
"""

from __future__ import annotations

import datetime as dt
import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

from . import config, frontmatter, gitutil, legacy, markdown, render_md, state, views
from .legacy import LegacyProject
from .model import Cycle, Project, RiteError, display

WE2002_CONFIG = """\
# rite.toml — generated by `rite.py migrate --from we2002`. Reference: the plugin's docs/CONFIG.md.

[project]
name = "{name}"
docs_language   = "pt-BR"
code_language   = "en-US"
commit_language = "en-US"

[paths]
cycles_root  = "docs/tasks"
archive_dir  = "docs/tasks/concluidos"
profiles_dir = "docs/prompts"
plans_dir    = "docs"
link_style   = "root-absolute"

[naming]
# the first template names new items; the second keeps items an earlier convention named by ID
task_file     = ["{{n:02}}-{{slug}}.md", "{{id}}.md"]
fix_id        = "CORR-{{prefix}}-{{n:03}}"
progress_file = "progresso.md"
fixes_file    = "correcoes-progresso.md"
profile_file  = "perfil-{{cycle}}.md"
pitfalls_file = "perfil-{{cycle}}.armadilhas.md"

[sections]
# the first title is the one Rite writes; the others are read as well
execution_log        = ["Log de Execução", "Log de Execução *(preenchido após execução)*"]
phase_checks         = "Verificações específicas por fase"
phase_label          = "Fase"
evidence             = "Evidência"
verification         = "Verificação"
files                = ["Arquivos a criar ou modificar", "Arquivos"]
gates                = "Gates deste ciclo"
serialized_resources = "Recursos serializados"
confirmed_decisions  = "Contexto essencial — decisões já confirmadas"

[profile]
# Raised to the largest legacy profile so the migration starts green; compact the profiles with
# /rite:retro (pitfalls go to the pitfalls file) and bring this back towards 12.
max_kb = {max_kb}

[vocab]
task_types = [{types}]
"""

TASK_STATUS = {
    "pendente": "pending", "em andamento": "in-progress", "concluído": "done", "concluido": "done",
    "concluída": "done", "bloqueado": "blocked", "bloqueada": "blocked", "pulado": "skipped",
    "pulada": "skipped", "cancelado": "skipped", "cancelada": "skipped",
}
FIX_STATUS = {
    "pendente": "pending", "em andamento": "in-progress", "concluída": "done", "concluída": "done",
    "concluído": "done", "concluido": "done", "envelhecida": "stale", "envelhecido": "stale",
    "obsoleta": "stale", "bloqueada": "blocked", "bloqueado": "blocked",
}
SEVERITY = {"crítica": "critical", "critica": "critical", "alta": "high", "média": "medium",
            "media": "medium", "baixa": "low"}
TYPE_MAP = {"fechamento": "closing"}
LEGACY_KEYS = {"fonte_de_verdade", "criticidade", "origem"}
PROVENANCE_MARK = "done_commit approximated from the last commit touching this file"
PROVENANCE_LINE = "_Migrated on {date}: " + PROVENANCE_MARK + "._"
EMOJI_STATUS = {"✅": "done", "⬜": "pending", "🔄": "in-progress", "❌": "blocked", "⏭": "skipped"}
_DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
_ID_IN = re.compile(r"\[?([A-Z][A-Z0-9]*-(?:TASK-)?\d+|CORR-[A-Z0-9]+-\d+)\]?")
_SECTION_REF = re.compile(r"^(\S+?\.md)\s*(?:§\s*(\d+(?:\.\d+)*)|#(\S+))?")


@dataclass
class Report:
    cycles: list[str] = field(default_factory=list)
    items: int = 0
    changed: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    unresolved_commits: list[str] = field(default_factory=list)
    approximated_commits: list[str] = field(default_factory=list)  # last commit touching the item file
    actions: list[dict] = field(default_factory=list)  # what the operator must decide, per item
    skipped: list[str] = field(default_factory=list)  # cycles already on the JSON state
    extra_keys: dict = field(default_factory=dict)  # fields outside Rite's vocabulary, kept: {key: count}
    comments: int = 0  # frontmatter comment lines dropped (the JSON has no comments)
    commit: str | None = None

    def as_dict(self) -> dict:
        return self.__dict__


# --- tables ------------------------------------------------------------------------
def _row(line: str, width: int) -> list[str]:
    """Cells of a table row; falls back to a plain split when code-span awareness breaks the width
    (an unbalanced backtick would otherwise swallow the rest of the row)."""
    cells = markdown.table_cells(line)
    if len(cells) == width:
        return cells
    stripped = line.strip().strip("|")
    plain = [c.strip() for c in re.split(r"(?<!\\)\|", stripped)]
    return plain if len(plain) == width else cells


def find_tables(text: str, must_have: tuple[str, ...]) -> list[tuple[int, int, list[str], list[list[str]]]]:
    """Every table whose header contains all ``must_have`` columns: [(start, end, header, rows)] by line.

    Legacy progress files can hold several state tables (an appendix for a second backlog); all of
    them carry state, so all of them are read.
    """
    lines = text.split("\n")
    found = []
    i = 0
    while i < len(lines) - 1:
        if lines[i].lstrip().startswith("|") and re.match(r"^\s*\|?\s*:?-{2,}", lines[i + 1]):
            header = [h.lower() for h in markdown.table_cells(lines[i])]
            j = i + 2
            while j < len(lines) and lines[j].lstrip().startswith("|"):
                j += 1
            if all(any(m in h for h in header) for m in must_have):
                found.append((i, j, header, [_row(ln, len(header)) for ln in lines[i + 2:j]]))
            i = j
        else:
            i += 1
    return found


def find_table(text: str, must_have: tuple[str, ...]) -> tuple[int, int, list[str], list[list[str]]] | None:
    tables = find_tables(text, must_have)
    return tables[0] if tables else None


def _col(header: list[str], *names: str) -> int | None:
    for n in names:
        for k, h in enumerate(header):
            if n in h:
                return k
    return None


def _first_id(cell: str) -> str | None:
    m = _ID_IN.search(cell)
    return m.group(1) if m else None


def _status_from_cell(cell: str, table: dict) -> str | None:
    for emoji, status in EMOJI_STATUS.items():
        if emoji in cell:
            return status
    low = re.sub(r"[\[\]x✓]", "", cell.lower()).strip()
    return table.get(low)


MOVED_TABLE_NOTE = ("_The state of these items now lives in the cycle's JSON state and in the generated table "
                    "above (`rite.py sync`)._")


def replace_tables(text: str, tables: list[tuple], region: str) -> str:
    """First state table becomes the generated region; later ones become a pointer to it.

    Why not keep them: a second copy of the state is exactly the drift the migration removes.
    """
    lines = text.split("\n")
    for index, (start, end, _, _) in reversed(list(enumerate(tables))):
        lines[start:end] = [views.begin_marker(region), views.END_MARKER] if index == 0 else [MOVED_TABLE_NOTE]
    return "\n".join(lines)


def replace_table(text: str, table: tuple, region: str) -> str:
    return replace_tables(text, [table], region)


# --- commits -----------------------------------------------------------------------
class CommitFinder:
    """Find the work commit of a legacy item from `git log` mentions of its ID."""

    def __init__(self, root: Path):
        self.root = root
        self.log: list[tuple[str, str, str]] = []
        if gitutil.is_repo(root):
            out = gitutil.run(root, "log", "--format=%h%x09%cs%x09%s%x09%b%x1e")
            for rec in out.split("\x1e"):
                parts = rec.strip("\n").split("\t", 3)
                if len(parts) >= 3:
                    self.log.append((parts[0], parts[1], parts[2] + "\n" + (parts[3] if len(parts) > 3 else "")))

    def last_touch(self, path: Path, done_on: str | None) -> str | None:
        """Fallback: the last commit that touched the item file on or before its done date."""
        rel = str(path.relative_to(self.root))
        attempts = ([[f"--before={done_on} 23:59:59"]] if done_on else []) + [[]]
        for extra in attempts:
            out = gitutil.run(self.root, "log", "-1", "--follow", "--format=%h", *extra, "--", rel,
                              check=False).strip()
            if out:
                return out
        return None

    def find(self, item_id: str, done_on: str | None) -> str | None:
        rx = re.compile(rf"(?<![\w-]){re.escape(item_id)}(?![\w-]|-\d)")
        hits = [(sha, date, msg) for sha, date, msg in self.log if rx.search(msg)]
        if done_on:
            hits = [h for h in hits if h[1] <= done_on] or hits
        work = [h for h in hits if not re.match(r"^(docs|chore)(\([^)]*\))?:", h[2])]
        pick = (work or hits)
        return pick[0][0] if pick else None  # newest first


# --- migration ---------------------------------------------------------------------
def _today() -> str:
    return dt.date.today().isoformat()


def _sot(project: Project, item_path: Path, raw: str, report: Report, item_id: str) -> str:
    m = _SECTION_REF.match(raw.strip())
    if not m:
        report.warnings.append(f"{item_id}: source_of_truth {raw!r} not understood; kept")
        report.actions.append({"item": item_id, "file": display(project.root, item_path),
                               "action": f"rewrite source_of_truth {raw!r} as <file>#<anchor>"})
        return raw
    path, section, anchor = m.group(1), m.group(2), m.group(3)
    target = (project.root / path.lstrip("/")) if path.startswith("/") else (item_path.parent / path)
    anchor = anchor or section
    if anchor and target.is_file() and markdown.has_anchor(target, anchor):
        return f"{path}#{anchor}"
    if anchor:
        # never invent an anchor: keep the file and say what the operator has to decide
        report.warnings.append(f"{item_id}: section {anchor!r} of {path} has no matching heading; kept file only")
        report.actions.append({
            "item": item_id, "file": display(project.root, item_path), "target": path, "section": anchor,
            "action": (f"either add a heading starting with '{anchor}' to {path} and set source_of_truth to "
                       f"{path}#{anchor}, or repoint it to an existing section (rite anchors {path})"),
        })
    return path


def migrate_cycle(project: Project, cycle_dir: Path, finder: CommitFinder, report: Report, *,
                  write: bool) -> None:
    progress = cycle_dir / project.progress_name
    fixes_file = cycle_dir / project.fixes_name
    ptext = progress.read_text(encoding="utf-8")
    meta, _ = frontmatter.parse(ptext)
    task_tables = find_tables(ptext, ("id", "status"))
    rows: dict[str, dict] = {}
    for _, _, header, trs in task_tables:
        c_id, c_st = _col(header, "id"), _col(header, "status")
        c_done, c_rev = _col(header, "concluída", "concluida"), _col(header, "revisad")
        c_phase = _col(header, "fase", "phase")
        for r in trs:
            if c_id is None or c_id >= len(r) or not (tid := _first_id(r[c_id])) or tid in rows:
                continue
            rows[tid] = {
                "status": _status_from_cell(r[c_st], TASK_STATUS) if c_st is not None and c_st < len(r) else None,
                "done_on": (_DATE.search(r[c_done]) or [None])[0] if c_done is not None and c_done < len(r) else None,
                "review": r[c_rev] if c_rev is not None and c_rev < len(r) else "",
                "phase": int(r[c_phase]) if c_phase is not None and c_phase < len(r)
                and r[c_phase].strip().isdigit() else None,
            }
    frows: dict[str, dict] = {}
    ftext = fixes_file.read_text(encoding="utf-8") if fixes_file.is_file() else ""
    fix_tables = find_tables(ftext, ("id", "status")) if ftext else []
    for _, _, header, trs in fix_tables:
        c_id, c_or = _col(header, "id"), _col(header, "origem", "origin")
        c_sev, c_st = _col(header, "criticidade", "severidade"), _col(header, "status")
        c_done = _col(header, "concluída", "concluida")
        if c_or == c_id:
            c_or = next((k for k, h in enumerate(header) if "origem" in h and k != c_id), None)
        for r in trs:
            if c_id is None or c_id >= len(r) or not (fid := _first_id(r[c_id])) or fid in frows:
                continue
            frows[fid] = {
                "origin": _first_id(r[c_or]) if c_or is not None and c_or < len(r) else None,
                "severity": SEVERITY.get(r[c_sev].strip().lower()) if c_sev is not None and c_sev < len(r) else None,
                "status": _status_from_cell(r[c_st], FIX_STATUS) if c_st is not None and c_st < len(r) else None,
                "done_on": (_DATE.search(r[c_done]) or [None])[0] if c_done is not None and c_done < len(r) else None,
            }

    cycle = project.load_cycle(cycle_dir)
    known = {i.path.name for i in cycle.items} | {project.progress_name, project.fixes_name}
    stray = sorted(p.name for p in cycle_dir.glob("*.md") if p.name not in known and ".template." not in p.name)
    if stray:
        report.warnings.append(f"{display(project.root, cycle_dir)}: not recognized by [naming], left as is: "
                               + ", ".join(stray[:8]) + (f" (+{len(stray) - 8})" if len(stray) > 8 else ""))
    prefixes = Counter(project.naming.parse_id(i.id)[1].get("prefix") for i in cycle.items
                       if project.naming.parse_id(i.id))
    prefix = str(meta.get("prefix") or (prefixes.most_common(1)[0][0] if prefixes else ""))
    name = str(meta.get("cycle") or (cycle_dir.name if cycle_dir != project.cycles_root
                                     and cycle_dir != project.archive_dir else prefix.lower()))
    report.cycles.append(f"{name} [{prefix}] {display(project.root, cycle_dir)}")
    new_meta = {"cycle": name, "prefix": prefix}
    prof = re.search(r"\*\*Perfil deste ciclo:\*\*\s*\[[^\]]*\]\(([^)]+)\)", ptext)
    if prof:
        new_meta["profile"] = prof.group(1)
    # the legacy table's row order was the execution order; keep it when it is not the ID order
    task_ids = {t.id for t in cycle.tasks}
    table_order = [i for i in rows if i in task_ids]
    if table_order and table_order != [t.id for t in cycle.tasks][:len(table_order)]:
        new_meta["order"] = table_order
        report.warnings.append(f"{display(project.root, progress)}: table order differs from ID order; "
                               f"kept as `order:` ({len(table_order)} tasks)")

    for item in cycle.items:
        report.items += 1
        f = dict(item.fields)
        up: dict = {}
        if item.kind == "task":
            row = rows.get(item.id, {})
            raw = str(f.get("status") or "").lower()
            status = row.get("status") or TASK_STATUS.get(raw, raw if raw in config.TASK_STATUSES else "pending")
            if row.get("status") and TASK_STATUS.get(raw) and TASK_STATUS[raw] != row["status"]:
                report.warnings.append(f"{item.id}: frontmatter says {raw!r}, table says {row['status']!r}; table wins")
            up["status"] = status
            if "fonte_de_verdade" in f or "source_of_truth" in f:
                up["source_of_truth"] = _sot(project, item.path, str(f.get("fonte_de_verdade") or
                                                                      f.get("source_of_truth")), report, item.id)
            if f.get("phase") is None:
                if row.get("phase") is not None:
                    up["phase"] = row["phase"]
                else:
                    # unknown is recorded as unknown; the operator assigns it
                    up["phase"] = None
                    report.actions.append({
                        "item": item.id, "file": display(project.root, item.path),
                        "action": "no phase in frontmatter or table: set `phase:` to the plan phase this "
                                  "task belongs to (phase-specific checks are keyed on it)",
                    })
            if f.get("type") in TYPE_MAP:
                up["type"] = TYPE_MAP[f["type"]]
            done_on = row.get("done_on") if status == "done" else None
            review = row.get("review", "")
            if status == "done":
                rdate = _DATE.search(review)
                up["reviewed_on"] = rdate.group(0) if rdate else "pending"
                if not done_on:
                    report.warnings.append(f"{item.id}: done without a date in the table")
            else:
                up["reviewed_on"] = None
            up["review_commit"] = f.get("review_commit")
        else:
            row = frows.get(item.id, {})
            raw = str(f.get("status") or "").lower()
            status = row.get("status") or FIX_STATUS.get(raw, raw if raw in config.FIX_STATUSES else "pending")
            if status == "blocked" and not f.get("unblocked_by"):
                # a blocked fix names the command that unblocks it; migrate has none to carry
                status = "pending"
                report.warnings.append(f"{item.id}: was blocked with no command that unblocks it; set pending "
                                       f"(rite.py mark {item.id} blocked --reason … --unblocked-by \"<command>\")")
            up["status"] = status
            origin = row.get("origin") or f.get("origin") or f.get("origem")
            if not origin:
                report.warnings.append(f"{item.id}: no origin in table or frontmatter")
            up["origin"] = origin
            up["severity"] = row.get("severity") or SEVERITY.get(str(f.get("criticidade", "")).lower()) \
                or f.get("severity") or "medium"
            if not row.get("severity") and not f.get("severity"):
                report.warnings.append(f"{item.id}: no severity found; set medium")
            done_on = row.get("done_on") if status in ("done", "stale") else None
        up["depends_on"] = item.depends_on
        up["done_on"] = done_on
        commit = None
        approximated = False
        if status == "done":
            commit = f.get("done_commit") or finder.find(item.id, done_on)
            if not commit and gitutil.is_repo(project.root):
                commit = finder.last_touch(item.path, done_on)
                if commit:
                    approximated = True
                    report.approximated_commits.append(item.id)
            if not commit:
                report.unresolved_commits.append(item.id)
        up["done_commit"] = commit
        text = item.path.read_text(encoding="utf-8")
        new = frontmatter.remove_fields(frontmatter.set_fields(text, up), LEGACY_KEYS)
        if approximated and PROVENANCE_MARK not in new:
            # the report is read once; the item is read every time the item is — record the doubt there
            new = markdown.append_to_section(new, project.section_titles("execution_log"),
                                             PROVENANCE_LINE.format(date=_today()))
        if new != text:
            report.changed.append(display(project.root, item.path))
            if write:
                item.path.write_text(new, encoding="utf-8", newline="\n")

    new_ptext = ptext
    if task_tables:
        new_ptext = replace_tables(new_ptext, task_tables, views.TASKS_REGION)
    else:
        report.warnings.append(f"{display(project.root, progress)}: no task table found; region appended")
    new_ptext = frontmatter.set_fields(new_ptext, new_meta)
    if write:
        progress.write_text(new_ptext, encoding="utf-8", newline="\n")
        if fix_tables:
            fixes_file.write_text(replace_tables(ftext, fix_tables, views.FIXES_REGION), encoding="utf-8",
                                  newline="\n")
        legacy.sync(project, project.load_cycle(cycle_dir))
    report.changed.append(display(project.root, progress))


def migrate_we2002(root: Path, *, write: bool, name: str = "") -> Report:
    root = root.resolve()
    report = Report()
    cfg_path = root / config.CONFIG_NAME
    if cfg_path.is_file():
        project = LegacyProject(config.load(root))
    else:
        types = _observed_types(root / "docs" / "tasks")
        profiles = list((root / "docs" / "prompts").glob("perfil-*.md"))
        max_kb = max([12, *((p.stat().st_size + 1023) // 1024 for p in profiles)])
        text = WE2002_CONFIG.format(name=name or root.name, types=", ".join(f'"{t}"' for t in types),
                                    max_kb=max_kb)
        project = LegacyProject(config.parse(root, text))
        if write:
            cfg_path.write_text(text, encoding="utf-8", newline="\n")
        report.changed.append(config.CONFIG_NAME)
    if not project.cycles_root.is_dir():
        raise RiteError(f"{display(root, project.cycles_root)} not found; is this a legacy repository?")
    finder = CommitFinder(root)
    dirs = [c for c in project._cycle_dirs(project.cycles_root)]
    if project.archive_dir.is_dir():
        if project.is_cycle_dir(project.archive_dir):
            dirs.append(project.archive_dir)
        dirs += [p for p in sorted(project.archive_dir.iterdir()) if p.is_dir() and project.is_cycle_dir(p)]
    for d in dirs:
        migrate_cycle(project, d, finder, report, write=write)
    if write:
        # the frontmatter layout is a step on the way: the state ends in the JSON
        converted = to_json(root, write=True, mid_migration=True)
        report.changed += [c for c in converted.changed if c not in report.changed]
        report.warnings += converted.warnings
    else:
        report.warnings.append("with --write, the state then moves from the frontmatter to the JSON files "
                               "(rite migrate --from frontmatter)")
    return report


def _observed_types(tasks_dir: Path) -> list[str]:
    seen: list[str] = []
    for f in sorted(tasks_dir.rglob("*.md")):
        try:
            fields, _ = frontmatter.parse(f.read_text(encoding="utf-8"))
        except (frontmatter.FrontmatterError, UnicodeDecodeError):
            continue
        t = fields.get("type")
        if isinstance(t, str) and t != "correção":
            t = TYPE_MAP.get(t, t)
            if t not in seen:
                seen.append(t)
    return seen or ["feature", "closing"]


# --- frontmatter -> JSON -----------------------------------------------------------
KNOWN_KEYS = {"id", "title", "type", "phase", "depends_on", "source_of_truth", "files", "resources", "repo",
              "status", "done_on", "done_commit", "reviewed_on", "review_commit", "origin", "severity",
              "unblocked_by"}


@dataclass
class _Plan:
    cycle: Cycle
    progress: dict
    fixes: dict
    writes: dict  # {path: bytes}


def _without_frontmatter(data: bytes, replacement: bytes | None) -> bytes:
    """``data`` with its leading frontmatter block replaced (or, with None, removed along with the
    blank lines after it). Bytes in, bytes out: the body is never decoded, so nothing in it changes."""
    lines = data.splitlines(keepends=True)
    if not lines or lines[0].rstrip(b"\r\n") != b"---":
        return data if replacement is None else replacement + data
    end = next((k for k in range(1, len(lines)) if lines[k].rstrip(b"\r\n") == b"---"), None)
    if end is None:
        raise RiteError("frontmatter opened with '---' but never closed")
    rest = lines[end + 1:]
    if replacement is None:
        while rest and not rest[0].strip():
            rest = rest[1:]
        return b"".join(rest)
    newline = b"\r\n" if lines[0].endswith(b"\r\n") else b"\n"
    return replacement.replace(b"\n", newline) + b"".join(rest)


def _comment_lines(text: str) -> int:
    fm, _ = frontmatter.split(text)
    count = 0
    for line in fm or []:
        stripped = line.strip()
        if stripped.startswith("#"):
            count += 1
        elif ":" in line and frontmatter._strip_comment(line.split(":", 1)[1])[1]:
            count += 1
    return count


def _same(old: Cycle, new: Cycle) -> list[str]:
    """Where a cycle read from the JSON differs from the same cycle read from the frontmatter."""
    diffs = []
    if old.meta != new.meta:
        diffs.append(f"cycle meta: {old.meta} != {new.meta}")
    for attr in ("name", "profile_path", "pitfalls_path"):
        if getattr(old, attr) != getattr(new, attr):
            diffs.append(f"{attr}: {getattr(old, attr)} != {getattr(new, attr)}")
    for kind, a, b in (("tasks", old.tasks, new.tasks), ("fixes", old.fixes, new.fixes)):
        if [i.id for i in a] != [i.id for i in b]:
            diffs.append(f"{kind} order: {[i.id for i in a]} != {[i.id for i in b]}")
            continue
        for x, y in zip(a, b):
            for attr in ("kind", "path", "n", "fields", "parse_error"):
                if getattr(x, attr) != getattr(y, attr):
                    diffs.append(f"{x.id} {attr}: {getattr(x, attr)!r} != {getattr(y, attr)!r}")
    return diffs


def _plan_cycle(old_project: LegacyProject, project: Project, cycle_dir: Path, report: Report) -> _Plan:
    archived = cycle_dir.resolve() in [d.resolve() for d in old_project.archived_dirs()]
    old = old_project.load_cycle(cycle_dir, archived=archived)
    where = display(project.root, cycle_dir)
    broken = [f"{display(project.root, i.path)}: {i.parse_error or 'no frontmatter'}"
              for i in old.items if i.parse_error or not i.fields]
    broken += [f"{display(project.root, i.path)}: no 'id'" for i in old.items if i.fields and not i.fields.get("id")]
    broken += [f"{display(project.root, i.path)}: 'file' is a reserved key" for i in old.items if "file" in i.fields]
    if broken:
        raise RiteError(f"{where}: cannot read " + "; ".join(broken))
    seen: dict[str, Path] = {}
    for i in old.items:
        if i.id in seen:
            raise RiteError(f"{where}: {i.id} is in {display(project.root, seen[i.id])} and "
                            f"{display(project.root, i.path)}; fix the duplicate first")
        seen[i.id] = i.path
    if {"schema", state.TASKS} & set(old.meta):
        raise RiteError(f"{display(project.root, old.progress_path)}: 'schema' and 'tasks' are reserved keys")

    progress = state.new_progress(old.meta)
    progress[state.TASKS] = legacy.entries(old, "task")
    fixes = state.new_fixes(old.name)
    fixes[state.FIXES] = legacy.entries(old, "fix")
    new = project.cycle_from_state(cycle_dir, progress, fixes, archived=archived)
    diffs = _same(old, new)
    if diffs:
        raise RiteError(f"{where}: the JSON would not read back as the frontmatter does; nothing written:\n  "
                        + "\n  ".join(diffs[:20]))

    writes: dict[Path, bytes] = {
        new.progress_state_path: state.dumps(progress).encode("utf-8"),
        new.fixes_state_path: state.dumps(fixes).encode("utf-8"),
    }
    writes[old.progress_path] = _without_frontmatter(old.progress_path.read_bytes(), None)
    for item in old.items:
        report.items += 1
        raw = item.path.read_bytes()
        text = raw.decode("utf-8")
        report.comments += _comment_lines(text)
        for key in item.fields:
            if key not in KNOWN_KEYS:
                report.extra_keys[key] = report.extra_keys.get(key, 0) + 1
        writes[item.path] = _without_frontmatter(raw, f"---\nid: {frontmatter.dump_value(item.id)}\n---\n"
                                                 .encode("utf-8"))
    for path, region, table in (
            (old.progress_path, render_md.TASKS_REGION, render_md.tasks_table(
                progress[state.TASKS], md_path=old.progress_path, cycle_dir=new.path, root=project.root,
                link_style=project.cfg.link_style)),
            (old.fixes_path, render_md.FIXES_REGION, render_md.fixes_table(
                fixes[state.FIXES], md_path=old.fixes_path, cycle_dir=new.path, root=project.root,
                link_style=project.cfg.link_style))):
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if render_md.extract_region(current, region) != table:
            report.warnings.append(f"{display(project.root, path)}: the {region} table was out of date; "
                                   "it is regenerated")
    report.cycles.append(f"{new.name} [{new.prefix}] {where}: {len(new.tasks)} tasks, {len(new.fixes)} fixes"
                         + (" (local)" if new.local else ""))
    return _Plan(cycle=new, progress=progress, fixes=fixes,
                 writes={k: v for k, v in writes.items() if not k.is_file() or k.read_bytes() != v})


def _refuse_unsafe_write(root: Path, paths: list[Path], *, commit: bool, check_dirty: bool = True) -> None:
    if not gitutil.is_repo(root):
        return
    if check_dirty:
        status = gitutil.run(root, "status", "--porcelain", "--", *(str(p.relative_to(root)) for p in paths
                                                                     if p.exists())).splitlines()
        # an untracked file has no committed version to lose; an edited tracked one would mix with ours
        dirty = [line for line in status if line.strip() and not line.startswith("??")]
        if dirty:
            raise RiteError("uncommitted changes in files the migration rewrites; commit or stash them first:\n"
                            + "\n".join(dirty))
    if commit and gitutil.run(root, "diff", "--cached", "--name-only").strip():
        raise RiteError("the index has staged changes; commit or unstage them first")


def to_json(root: Path, *, write: bool, commit: bool = False, mid_migration: bool = False) -> Report:
    """Move every cycle's state from frontmatter to the JSON files. All cycles or none.

    ``mid_migration``: the files were just rewritten by an earlier migration step (`--from we2002`),
    so their uncommitted changes are that step's, not someone's work in progress."""
    root = root.resolve()
    cfg = config.load(root)
    old_project, project = LegacyProject(cfg), Project(cfg)
    report = Report()
    dirs = list(dict.fromkeys(old_project._cycle_dirs(old_project.cycles_root) + old_project.archived_dirs()))
    plans = []
    for d in dirs:
        if not project.is_legacy_dir(d):
            report.skipped.append(display(root, d))
            continue
        plans.append(_plan_cycle(old_project, project, d, report))
    report.changed = [display(root, p) for plan in plans for p in plan.writes]
    if not write or not plans:
        return report

    paths = [p for plan in plans for p in plan.writes]
    git = gitutil.is_repo(root)
    _refuse_unsafe_write(root, paths, commit=commit, check_dirty=git and not mid_migration)
    for plan in plans:
        for path, data in plan.writes.items():
            path.write_bytes(data)
    tracked: list[Path] = []
    for plan in plans:
        cycle = project.load_cycle(plan.cycle.path, archived=plan.cycle.archived)
        diffs = _same(plan.cycle, cycle)
        if diffs:
            raise RiteError(f"{display(root, cycle.path)}: read back differs after writing (git restore the "
                            "cycle and report it):\n  " + "\n  ".join(diffs[:20]))
        changed = views.sync(project, cycle)
        if not cycle.local:
            tracked += [*plan.writes, *changed]
    if commit and git and tracked:
        report.commit = gitutil.commit_paths(root, list(dict.fromkeys(tracked)),
                                             "chore(rite): move cycle state to JSON" if
                                             cfg["commit"]["style"] == "conventional" else
                                             "rite: move cycle state to JSON")
    return report


# --- --from graph ----------------------------------------------------------------------
_MERMAID_OPEN = re.compile(r"^\s{0,3}(```|~~~)\s*mermaid\b", re.IGNORECASE)
_ARROW = re.compile(r"\s*(?:<?-->|<?==>|<?-\.->|---|-\.-)(?:\|[^|]*\|)?\s*")
_NODE = re.compile(r"^([\w-]+)\s*(?:[\[({>]+\s*\"?(.*?)\"?\s*[\])}]+)?")


def _graph_edges(mermaid: str, ids: list[str]) -> tuple[list[tuple[str, str]], set[str]]:
    """Best-effort (from, to) task-ID edges of a hand-drawn flowchart, and the node names no task ID
    could be read from. A node is a task when its name or its label holds the ID."""
    def find_id(text: str) -> str | None:
        hits = [i for i in ids if i in text]
        return max(hits, key=len) if hits else None

    norm = {re.sub(r"\W", "", i).lower(): i for i in ids}
    labels: dict[str, str] = {}
    chains = []
    for raw in mermaid.splitlines():
        line = raw.split("%%", 1)[0].strip()
        if not line or re.match(r"^(graph|flowchart|subgraph|end|classDef|class|style|linkStyle|click)\b", line):
            continue
        sides = _ARROW.split(line)
        chain = []
        for side in sides:
            group = []
            for part in side.split("&"):
                m = _NODE.match(part.strip())
                if not m:
                    continue
                name, label = m.group(1), m.group(2)
                if label:
                    labels[name] = label
                group.append(name)
            chain.append(group)
        if len(chain) > 1:
            chains.append(chain)

    unresolved: set[str] = set()

    def resolve(name: str) -> str | None:
        found = find_id(labels.get(name, "")) or find_id(name) or norm.get(re.sub(r"\W", "", name).lower())
        if not found:
            unresolved.add(name)
        return found

    edges = []
    for chain in chains:
        for left, right in zip(chain, chain[1:]):
            for a in left:
                for b in right:
                    pair = (resolve(a), resolve(b))
                    if all(pair) and pair not in edges:
                        edges.append(pair)
    return edges, unresolved


def _with_graph_region(text: str, titles: list[str]) -> tuple[str, str | None]:
    """(text with an empty graph region in place of the hand-drawn block, that block's body or None).
    The region goes where the graph was: the first mermaid block of the graph section; else the top of
    that section; else a new section before the tasks table."""
    lines = text.splitlines(keepends=True)
    eol = "\r\n" if "\r\n" in text else "\n"
    region = [render_md.begin_marker(render_md.GRAPH_REGION) + eol, render_md.END_MARKER + eol]
    fence = None
    start = level = None
    end = len(lines)
    for i, line in enumerate(lines):
        m = markdown._FENCE_RE.match(line)
        if m:
            fence = m.group(1) if fence is None else (None if m.group(1) == fence else fence)
            continue
        if fence:
            continue
        h = markdown._HEADING_RE.match(line.rstrip("\r\n"))
        if not h:
            continue
        if start is None:
            if any(markdown.title_matches(h.group(2), t) for t in titles):
                start, level = i, len(h.group(1))
        elif len(h.group(1)) <= level:
            end = i
            break
    if start is not None:
        for i in range(start + 1, end):
            m = _MERMAID_OPEN.match(lines[i])
            if not m:
                continue
            close = next((j for j in range(i + 1, end) if lines[j].strip().startswith(m.group(1))), None)
            if close is None:
                break
            body = "".join(lines[i + 1:close])
            return "".join(lines[:i] + region + lines[close + 1:]), body
        return "".join(lines[:start + 1] + [eol] + region + lines[start + 1:]), None
    section = [f"## {titles[0]}{eol}", eol, *region, eol]
    tasks_at = next((i for i, line in enumerate(lines)
                     if render_md.begin_marker(render_md.TASKS_REGION) in line), None)
    if tasks_at is None:
        if lines and not lines[-1].endswith("\n"):
            lines[-1] += eol
        return "".join(lines + [eol] + section), None
    # before the tasks table's own section; the document title (level 1) is not one
    at = tasks_at
    for i in range(tasks_at - 1, -1, -1):
        h = markdown._HEADING_RE.match(lines[i].rstrip("\r\n"))
        if h:
            at = i if len(h.group(1)) > 1 else tasks_at
            break
    return "".join(lines[:at] + section + lines[at:]), None


def graph_regions(root: Path, *, write: bool, commit: bool = False) -> Report:
    """Swap every cycle's hand-drawn dependency graph for the generated region. Idempotent."""
    root = root.resolve()
    cfg = config.load(root)
    project = Project(cfg)
    report = Report()
    titles = project.section_titles("dependency_graph")
    writes: dict[Path, bytes] = {}
    cycles = []
    for d in project._cycle_dirs(project.cycles_root) + project.archived_dirs():
        if project.is_legacy_dir(d):
            raise RiteError(f"{display(root, d)} is a cycle from before the JSON state: run "
                            "`rite migrate --from frontmatter --write` first")
        cycle = project.load_cycle(d)
        path = cycle.progress_path
        text = path.read_bytes().decode("utf-8") if path.is_file() else ""
        if render_md.begin_marker(render_md.GRAPH_REGION) in text:
            report.skipped.append(cycle.name)
            continue
        new, drawn = _with_graph_region(text, titles)
        tasks = [i.fields | {"id": i.id} for i in cycle.tasks]
        new = render_md.replace_region(new, render_md.GRAPH_REGION, render_md.dependency_graph(
            tasks, phase_label=project.section_title("phase_label")))
        if drawn is not None:
            ids = [t["id"] for t in tasks]
            edges, unresolved = _graph_edges(drawn, ids)
            deps = {t["id"]: set(render_md._deps(t)) for t in tasks}
            for a, b in edges:
                if a not in deps.get(b, set()):
                    report.warnings.append(f"{cycle.name}: {a} --> {b} is in the hand-drawn graph, not in "
                                           f"{b}'s depends_on; if it holds: rite set {b} --depends-on …")
            if unresolved:
                report.warnings.append(f"{cycle.name}: hand-drawn nodes naming no task, not compared: "
                                       + ", ".join(sorted(unresolved)))
        report.cycles.append(f"{cycle.name}: " + ("hand-drawn graph replaced" if drawn is not None else
                                                  "graph region added"))
        report.items += len(tasks)
        writes[path] = new.encode("utf-8")
        cycles.append(cycle)
    report.changed = [display(root, p) for p in writes]
    if not write or not writes:
        return report
    _refuse_unsafe_write(root, list(writes), commit=commit)
    for path, data in writes.items():
        path.write_bytes(data)
    tracked = [c.progress_path for c in cycles if not c.local]
    if commit and gitutil.is_repo(root) and tracked:
        report.commit = gitutil.commit_paths(root, tracked,
                                             "chore(rite): generate dependency graphs from depends_on" if
                                             cfg["commit"]["style"] == "conventional" else
                                             "rite: generate dependency graphs from depends_on")
    return report
