"""Generated commands must match their body and the parts they declare."""

import io
import sys
import unittest
from contextlib import redirect_stdout, redirect_stderr
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import build_commands as bc  # noqa: E402


class BuildCommandsTest(unittest.TestCase):
    def test_every_command_is_in_sync(self):
        out, err = io.StringIO(), io.StringIO()
        with redirect_stdout(out), redirect_stderr(err):
            code = bc.main(["--check"])
        self.assertEqual(code, 0, err.getvalue() or out.getvalue())

    def test_each_body_declares_existing_parts(self):
        names = bc.command_names()
        self.assertTrue(names)
        for name in names:
            front, body = bc.split_frontmatter(
                (ROOT / "commands" / f"_{name}.body.md").read_text(encoding="utf-8"))
            parts, kept = bc.declared_parts(front)
            self.assertTrue(any(line.startswith("description:") for line in kept), name)
            self.assertNotIn("parts:", "".join(kept), name)
            self.assertIn(bc.MARKER, body, name)
            for part in parts:
                self.assertTrue((ROOT / "parts" / f"{part}.md").is_file(), f"{name}: {part}")

    def test_every_part_is_used_by_some_command(self):
        used = set()
        for name in bc.command_names():
            front, _ = bc.split_frontmatter(
                (ROOT / "commands" / f"_{name}.body.md").read_text(encoding="utf-8"))
            used.update(bc.declared_parts(front)[0])
        unused = sorted(p.stem for p in (ROOT / "parts").glob("*.md") if p.stem not in used)
        self.assertEqual(unused, [], "a rule nobody declares is a rule nobody follows")

    def test_generated_file_is_marked_as_generated(self):
        for name in bc.command_names():
            text = (ROOT / "commands" / f"{name}.md").read_text(encoding="utf-8")
            self.assertIn("Generated by tools/build_commands.py", text, name)


if __name__ == "__main__":
    unittest.main()
