#!/usr/bin/env node
// Generates src/index.mjs: one re-export per module in src/, sorted. Never edit the output.
// Usage: node tools/gen-exports.mjs [--check]
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "src", "index.mjs");

const modules = readdirSync(join(root, "src"))
  .filter((f) => f.endsWith(".mjs") && f !== "index.mjs")
  .sort();

const lines = [
  "// GENERATED by tools/gen-exports.mjs -- do not edit; edit the generator and re-run it.",
  ...modules.map((f) => `export * from "./${f}";`),
  "",
];
const body = lines.join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {
    current = "";
  }
  if (current !== body) {
    console.error("src/index.mjs is out of date; run: node tools/gen-exports.mjs");
    process.exit(1);
  }
  console.log("src/index.mjs is up to date");
} else {
  writeFileSync(out, body);
  console.log(`wrote src/index.mjs (${modules.length} module(s))`);
}
