#!/usr/bin/env python3
"""Assemble `commands/<name>.md` from its body and the shared parts it declares.

A command is loaded in one turn, so the rules it obeys must be inside it: reading eight fragments
afterwards was measured as a third of an invocation's cost. Each rule is still written once, in
`parts/`, and this tool inlines the ones a command declares.

    python tools/build_commands.py            # write commands/*.md
    python tools/build_commands.py --check    # fail if a command on disk differs

The source of a command is `commands/_<name>.body.md`: frontmatter with `parts: [cli, state, …]`
(dropped from the output), then prose with a `<!-- rite:parts -->` marker where they go.
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MARKER = "<!-- rite:parts -->"
HEADER = "<!-- Generated by tools/build_commands.py from _{name}.body.md + parts/. -->"


def split_frontmatter(text: str) -> tuple[list[str], str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise SystemExit("a command body starts with frontmatter")
    end = next(i for i, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    return lines[1:end], "\n".join(lines[end + 1:]).lstrip("\n")


def declared_parts(front: list[str]) -> tuple[list[str], list[str]]:
    """(parts, frontmatter without the parts line)."""
    parts: list[str] = []
    kept: list[str] = []
    for line in front:
        key, _, value = line.partition(":")
        if key.strip() == "parts":
            parts = [p.strip() for p in value.strip().strip("[]").split(",") if p.strip()]
        else:
            kept.append(line)
    return parts, kept


def build(name: str) -> str:
    body_path = ROOT / "commands" / f"_{name}.body.md"
    front, body = split_frontmatter(body_path.read_text(encoding="utf-8"))
    parts, front = declared_parts(front)
    texts = []
    for part in parts:
        path = ROOT / "parts" / f"{part}.md"
        if not path.is_file():
            raise SystemExit(f"{body_path.name} declares part {part!r}, which does not exist")
        texts.append(path.read_text(encoding="utf-8").strip())
    block = "\n\n".join(texts)
    if MARKER not in body:
        raise SystemExit(f"{body_path.name} has no {MARKER} marker")
    out = "---\n" + "\n".join(front) + "\n---\n\n" + HEADER.format(name=name) + "\n\n" + body
    return out.replace(MARKER, block).rstrip() + "\n"


def command_names() -> list[str]:
    return sorted(p.name[1:-len(".body.md")] for p in (ROOT / "commands").glob("_*.body.md"))


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--check", action="store_true", help="only report differences")
    p.add_argument("--max-kb", type=int, default=8, help="size limit per generated command")
    args = p.parse_args(argv)

    problems: list[str] = []
    for name in command_names():
        target = ROOT / "commands" / f"{name}.md"
        wanted = build(name)
        if len(wanted.encode("utf-8")) > args.max_kb * 1024:
            problems.append(f"{name}.md is {len(wanted.encode('utf-8')) // 1024} KB "
                            f"> {args.max_kb} KB; condense the body or drop a part")
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current == wanted:
            continue
        if args.check:
            diff = difflib.unified_diff(current.splitlines(), wanted.splitlines(),
                                        f"{name}.md (on disk)", f"{name}.md (built)", lineterm="")
            problems.append("\n".join(list(diff)[:40]) or f"{name}.md differs")
        else:
            target.write_text(wanted, encoding="utf-8", newline="\n")
            print(f"wrote commands/{name}.md ({len(wanted.encode('utf-8'))} B)")
    if problems:
        print("\n".join(problems), file=sys.stderr)
        return 1
    if args.check:
        print(f"{len(command_names())} command(s) match their body and parts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
